### ISSUE TITLE
run ios & doctor TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by dseeker** [apache/incubator-weex-cli#546]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [X] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [X] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- Check weex-toolkit verison (Run `weex -v`)
```
2.0.0-beta.26 (Core 2.0.0-beta.26)
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/doctor : v2.0.0-beta.20
- @weex-cli/lint : v2.0.0-beta.2
- @weex-cli/debug : v2.0.0-beta.26
- @weex-cli/compile : v2.0.0-beta.24
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/build : v2.0.0-beta.15
- @weex-cli/plugin : v2.0.0-beta.22

```
- Detect what's wrong with your environment (Run `weex doctor`)
```
Time: 10:20:51, verify if there is an update
⠏ TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at <anonymous> (/Users/dseeker/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.26@@weex-cli/core/src/cli/cli.ts:540:46)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dseeker/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.26@@weex-cli/core/lib/cli/cli.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```
- Which platform (Win/Mac/Ubuntu..)
macOS 10.13.6

## The key error stack message.
```
Time: 10:20:51, verify if there is an update
⠏ TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at <anonymous> (/Users/dseeker/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.26@@weex-cli/core/src/cli/cli.ts:540:46)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dseeker/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.26@@weex-cli/core/lib/cli/cli.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link)
Unsure. Was working until last week. npm run web still works but npm run ios is stuck on this error

**Comment by erha19** [comment]
@dseeker I have fixed this issue, please try `weex repair` command to fix it.

**Comment by dseeker** [comment]
repair worked and doctor gives this result, thanks for the quick response

```
✔ Weex Cli Environment (v2.0.0-beta.27, on darwin 17.7.0):

[✔] @weex-cli/core  - core module for the weex-toolkit
[✔] @weex-cli/generator - Generator for weex-toolkit
[✔] @weex-cli/doctor - Doctor module for weex-toolkit
[✔] @weex-cli/lint - Lint module for weex-toolkit
[✔] @weex-cli/debug - Module for debug weex file
[✔] @weex-cli/compile - Plugin for compile weex file.
[✔] @weex-cli/run - module for running iOS/Android/Web platform with weex-toolkit
[✔] @weex-cli/device - module for lanuch device with weex-toolkit
[✔] @weex-cli/build - Build module for weex-toolkit
[✔] @weex-cli/plugin - Module for manage weex plugin and create plugin project

```

**Comment by dseeker** [comment]
I'm still getting this after about two to three weeks, everything works, but update returns an error
```
> weex run ios

Time: 17:1:19, verify if there is an update
[✖] Unkonw error with checking [@weex-cli/generator], can't found @weex-cli/generator latest version
[✖] Unkonw error with checking [@weex-cli/doctor], can't found @weex-cli/doctor latest version
[✖] Unkonw error with checking [@weex-cli/lint], can't found @weex-cli/lint latest version
[✖] Unkonw error with checking [@weex-cli/debug], can't found @weex-cli/debug latest version
[✖] Unkonw error with checking [@weex-cli/compile], can't found @weex-cli/compile latest version
[✖] Unkonw error with checking [@weex-cli/run], can't found @weex-cli/run latest version
[✖] Unkonw error with checking [@weex-cli/device], can't found @weex-cli/device latest version
[✖] Unkonw error with checking [@weex-cli/build], can't found @weex-cli/build latest version
[✖] Unkonw error with checking [@weex-cli/plugin], can't found @weex-cli/plugin latest version
```
